### ISSUE TITLE
Access to restricted URI denied

### ISSUE THREAD

**Issue by mcepl** [tuxgasy/SyncDav#2]
When installing your app, I have entered my credentials for my OwnCloud instance (owncloud-7.0.4-16.1 on CentOS 6.6), reset my address book (don't worry, I have backups; BTW, it would be nice to make some notification that the reset is done), and started synchronization. SyncDav shown 0/8xx contacts syncrhonized. After waiting for a minute or so (when the notification didn't change) I have killed the app. When I have restarted it again (without doing anything) I got this into logcat:
```
I/SyncDav ( 7389): Content JS LOG: DEBUG jsDAVlib: 1421920345124 - https://hubmaier.ceplovi.cz/remote.php/carddav/addressbooks/matej/contacts ERROR: NS_ERROR_DOM_BAD_URI: Access to restricted URI denied 
I/SyncDav ( 7389):     at jsDAVlib_debug (app://{8f60ec40-243a-4a56-aac4-b1265e93b058}/js/lib/jsDAVlib/src/jsDAVlib.js:12:4)
I/SyncDav ( 7389): Content JS LOG: DEBUG jsDAVlib: 1421920345131 - ERROR: NS_ERROR_DOM_BAD_URI: Access to restricted URI denied 
I/SyncDav ( 7389):     at jsDAVlib_debug (app://{8f60ec40-243a-4a56-aac4-b1265e93b058}/js/lib/jsDAVlib/src/jsDAVlib.js:12:4)
```
Looking at https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest it seems you have to do a little bit more magic, like setting `mozSystem` flag of `objParameters` object. Perhaps something more?

**Comment by tuxgasy** [comment]
SyncDav load your contacts before saving. So it can take a long time if you have a lot of contacts.

You can debug the app with [WebIDE](https://developer.mozilla.org/en-US/docs/Tools/WebIDE) or [App Manager](https://developer.mozilla.org/en-US/Firefox_OS/Using_the_App_Manager).

**Comment by mcepl** [comment]
You are probably right. It would be awesome if there was some more progress information (not only `Updating 0/800` but also `Downloading 0/800`. Besides, why these things are not done in parallel?

**Comment by tuxgasy** [comment]
I have 102 contacts and it's take 30 secondes to synchronize. I will investigate if it's possible to do in parallel.
